# ___  __    ___  _________        ________  ___      ___ ________        ________  ___       ___  ___  ________
#|\  \|\  \ |\  \|\___   ___\     |\   __  \|\  \    /  /|\   __  \      |\   __  \|\  \     |\  \|\  \|\   ____\
#\ \  \/  /|\ \  \|___ \  \_|     \ \  \|\  \ \  \  /  / | \  \|\  \     \ \  \|\  \ \  \    \ \  \\\  \ \  \___|_
# \ \   ___  \ \  \   \ \  \       \ \   ____\ \  \/  / / \ \   ____\     \ \   ____\ \  \    \ \  \\\  \ \_____  \
#  \ \  \\ \  \ \  \   \ \  \       \ \  \___|\ \    / /   \ \  \___|      \ \  \___|\ \  \____\ \  \\\  \|____|\  \
#   \ \__\\ \__\ \__\   \ \__\       \ \__\    \ \__/ /     \ \__\          \ \__\    \ \_______\ \_______\____\_\  \
#    \|__| \|__|\|__|    \|__|        \|__|     \|__|/       \|__|           \|__|     \|_______|\|_______|\_________\
#                                                                                                         \|_________|
# KitPvP Plus
# Download here: http://nckr.link/kpp
# config.yml

update:
  alert: true
  # Coming soon
  auto-download: false
  # In minutes
  re-check-alert: 10
  # If update alerts are enabled, should it check for beta updates
  notify-beta: false

data-storage:
  # mysql, mongo, flat
  type: flat
  # Only needed for mysql and mongo
  host: localhost
  port: 3306
  # Only needed for MySQL
  database: "KitPVP"
  authentication:
    # Must be enabled for mysql. Leave password in blank quotes for empty password
    enabled: true
    username: root
    password: ""

enable-signs: true
enable-guis: true
# If true, the player's statistics will not be altered when they get killed naturally/by a mob
disable-pve-stats: false

exp:
  kills: 25
  deaths: 5

death-sound: "ENTITY_ENDERMAN_DEATH"
arrow-hit-sound: "BLOCK_NOTE_BLOCK_PLING"

filler-item: "STAINED_GLASS_PANE"
abilities:
  tnt-shooter:
    displayname: "&cTNT Shooter"
    material: "TNT"
    amount: 10
    lore:
      - "&7[Right Click] An item to throw &ctnt &7at your opponents."
  fireball:
    displayname: "&fGhast"
    material: "FIREBALL"
    amount: 10
    lore:
      - "&7[Right Click] An item to shoot &6fireballs &7at your opponents."
  sonic:
    displayname: "&9Sonic"
    material: "LAPIS_BLOCK"
    amount: 1
    lore:
      - "&7[Right Click] An item you click to go the &9speed of light&7."
  fireman:
    displayname: "&aFireman"
    material: "BUCKET"
    amount: 1
    lore:
      - "&7[Right Click] An item to put out yourself if you are &6fire&7."

# When soup is used, should the empty bowl be removed from the inventory
remove-empty-soup: true

# Leave blank to have none
on-join-kit: ""
on-respawn-kit: ""

kill-commands:
  - "tell %player% You died to %killer%"
  - "tell %killer% You killed %player%"

scoreboard:
  enabled: true
  disabled-worlds:
    - EXAMPLE_WORLD
  spawn:
    title: "&b&lServer &7❘ &fKitPvP"
    board:
      - "&7%bar%"
      - "&eKills: &b%kills%"
      - "&eDeaths: &b%deaths%"
      - "&eKillstreak: &b%killstreak%"
      - "&eKDR: &b%kdr%"
      - ""
      - "&b&oserver.com"
      - "&7%bar%"
  arena:
    title: "&b&lServer &7❘ &fKitPvP"
    board:
      - "&7%bar%"
      - "&eKills: &b%kills%"
      - "&eDeaths: &b%deaths%"
      - "&eKillstreak: &b%killstreak%"
      - "&eKDR: &b%kdr%"
      - ""
      - "&b&oserver.com"
      - "&7%bar%"