name: KitPvPPlus
version: ${project.version}
main: wtf.nucker.kitpvpplus.KitPvPPlus
load: POSTWORLD
authors: [Nucker]
description: ${project.description}
website: nucker.me
api-version: 1.13
loadbefore:
  - Essentials
softdepend:
  - PlaceholderAPI
  - Vault
  - WorldGuard